language: csharp

services:  
    - docker

before_install:  
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:  
    - docker build --no-cache -t katyayermolayeva/amazon-killers
    - docker tag katyayermolayeva/amazon-killers:newest katyayermolayeva/amazon-killers:v1
    - docker push katyayermolayeva/amazon-killers
    
after_success:
    - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
    - heroku plugins:install heroku-container-registry
    - docker login -e _ -u _ --password=$HEROKU_API_KEY registry.heroku.com
    - heroku container:push web --app $HEROKU_APP_NAME
